spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_v2?allowPublicKeyRetrieval=true&useSSL=falseuseUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: bloger
    password: Uncleming0.
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: localhost
    username: uncleming
    password: uncleming0.
    virtual-host: blog
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: um.article.exchange
    publisher-confirm-type: correlated
logging:
  level:
    root: warn
    cn.guanjm: info
  file:
    name: log/blog-pro.log
server:
  port: 8080
um:
  jwt:
    secret: uncleming@login(Auth^30)blog # 登录校验的密钥
    pubKeyPath: /usr/local/blog/rsa/rsa.pub # 公钥地址
    priKeyPath: /usr/local/blog/rsa/rsa.pri # 私钥地址
    expire: 240 # 过期时间,单位分钟
    cookieName: UM_TOKEN
  upload:
    baseURL: /usr/local/webserver/upload/images/blog/
    allowTypes:
      - image/png
      - image/jpg
      - image/jpeg
      - image/gif