spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_v2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: guanjiaming
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: um.article.exchange
    publisher-confirm-type: correlated

logging:
  level:
    root: info
    cn.guanjm: debug
  file:
    name: log/blog-dev.log
um:
  jwt:
    secret: um@login(Auth^30)blog # 登录校验的密钥ly@Login(Auth}*^31)&yun6%
    pubKeyPath: /Users/guanjiaming/Documents/project/blog-V2/blog-java-maven/rsa/rsa.pub # 公钥地址
    priKeyPath: /Users/guanjiaming/Documents/project/blog-V2/blog-java-maven/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: UM_TOKEN
  upload:
    baseURL: /Users/guanjiaming/Documents/project/blog-V2/blog-java-maven/upload/
    allowTypes:
      - image/png
      - image/jpg
      - image/jpeg
      - image/gif