spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  jackson:
    time-zone: GMT-8

mybatis:
  type-aliases-package: cn.guanjm.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql